print("╔╦═╦╗╔══╗╔══╗╔══╗  ╔╗╔╗╔══╗╔═╗╔╦╗")
print("║║║║║╚║║╝║═╦╝╚║║╝  ║╚╝║║╔╗║║╔╝║╔╝")
print("║║║║║╔║║╗║╔╝─╔║║╗  ║╔╗║║╠╣║║╚╗║╚╗")
print("╚═╩═╝╚══╝╚╝──╚══╝  ╚╝╚╝╚╝╚╝╚═╝╚╩╝")
print("─────────────────  ──────────────")
print("ᴛᴏᴏʟs ᴍᴀᴅᴇ ʙʏ ᴢᴄᴀɪɴᴢ")
import time
print()
time.sleep(1)
print("GUNAKAN TOOLS INI DENGAN BIJAK")
print()
time.sleep(1)
print("PILIH MENU:")
print()
time.sleep(0.75)
print("1. Wifi Hack")
time.sleep(0.75)
print("2. About")
print("\n" * 3)
a=input("\n>")
if a == "1":
	print("\n" * 20)
print("╔╦═╦╗╔══╗╔══╗╔══╗  ╔╗╔╗╔══╗╔═╗╔╦╗")
print("║║║║║╚║║╝║═╦╝╚║║╝  ║╚╝║║╔╗║║╔╝║╔╝")
print("║║║║║╔║║╗║╔╝─╔║║╗  ║╔╗║║╠╣║║╚╗║╚╗")
print("╚═╩═╝╚══╝╚╝──╚══╝  ╚╝╚╝╚╝╚╝╚═╝╚╩╝")
print("─────────────────  ──────────────")
print("ᴛᴏᴏʟs ᴍᴀᴅᴇ ʙʏ ᴢᴄᴀɪɴᴢ")
print()
time.sleep(1)
print("GUNAKAN TOOLS INI DENGAN BIJAK")
print()
time.sleep(1)
print("TULIS NAMA WIFI TARGET:")
print()
b=input()
